version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    networks:
      - gerenciamento-notas_app-network
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - gerenciamento-notas_app-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_DATABASE: gerenciamento_notas
      MYSQL_USER: laravel
      MYSQL_PASSWORD: "1234"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gerenciamento-notas_app-network

volumes:
  dbdata:

networks:
  gerenciamento-notas_app-network:
    driver: bridge
